jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest
             
    - stage: release to pypi
      if: type = push AND tag IS present
      language: python
      catch: pip
      python:
        - "3.6"
      script:
        - echo "Skipping tests"
      deploy:
        provider: pypi
        user: meituanqa
        password:
          secure: "B8ua64zQJyydVVVWIMG3lCn3yjca4ZFtxYiThQXKIAh/dkDr40B6Em7zCgjb5n1d6A2MhkQKwBcAaEbhX7W2zEjQv6PAeV42QOYgB/W9pdBGbUh31ZXQSwE0mpQdAH0WCCdLOpB0F0e95JDDtVhjQlhAYbrVSpqYAhIeq79rBtJNvxRRrHjdzHYW+qbwFjbWxlO3c06TEpU2dTwHPdBx9iup4utmEmA51HIQkItDzNdHcRCPLyZvr+P27xp9ikrYgg2He/Usyq/zC6V7NhtMaPga8sf4jMPoYEvW6V/fFyRssvlytpdTAeSyZRAyHRl6cw6fyehqfbiTdhFNzUMRWkg/Oijd0+S4EbpmY5DX4+mVDuM0EU6eizchvT9sjwZcSrlEBK74oyWtQOfLy0yl5+T/Eny3pqLaF1wBGARyMw3Nkviijc1llh/wHgsT7eYUDAoTm7XdEPmtv22FVL7OXCrUbuPRdkyzy0x8WSit9gJfj4IJ0L5kdiNoSBtGw1XASgIyJJUwc3ke+sGp4WmrveYK+Lrp/DCgMH/VtSdSvWkuKAJ1c9Eck8NhD2ZJvgQaKGPgmE3Q+3fMbZcI2U3gJeqkGXgNhSGGDau5694vTFdbs3bbX/dS72ahcCu9hkTPEV+oFWXDmXD6I/q8/hEJ2OhxOmdS7EeV36b47h8pWLA="
        on:
          tags: true
