jobs:
  include:
    - stage: unit test
      language: python
      catch: pip
      python:
        - "3.6"
      # command to install dependencies
      install:
        - pip install -r requirements.txt
        - pip install .
      # command to run tests
      script: pytest
             
    - stage: release to pypi
      if: type = push AND tag IS present
      language: python
      catch: pip
      python:
        - "3.6"
      script:
        - echo "Skipping tests"
      deploy:
        provider: pypi
        user: Addison_Gao
        password:
          secure: "zTXn5Df2mzZ5s4JVvbRgCsADApu3R3cOtyuQf1vMZMmFQh+CID+ta0xhUWV5SdnSwPIV82xbZ5EEDOKFNrKokOSe3rXX6596faOHVU86A/uMZXburWC6hjMVcW4soaDIj/ObQ8yX0gJ91IWTakj2y1Bx4pFS/cyLpot/pgUF1eLljjF0GiAtIBdDrLypYt2B6fhubVprmvU5xSsRoa2NorHk0XO0EWEMCt4TsMTc5N8AaOP3lBclQe3xypVG48za513oq+/Ju9bxZsMPC5oPGwqRN0tkC0WzkiregchuCSvARozPOpKaYNY28A7p8CvdHKt6Dxk22+izTgZw5s/WWt+AWL+Qs/wX5FKtFa/T9iL7/DrZfZwbqvQ/+emgBeWmaHaa1QoVNC7Rt20sAkZI3Qab5stYPMrs0JhjvrY83rbD8KU0o80StO0u2KR8ZC2lWF3PJhC4yoV9820BpFKGR7zAJIcxrckjatMlRmGSCBvGlVVMrWKxPngQsZAyrBJlJbtHc9kiwXbQkXHhStj1eEpVCfYYYmArqAzVAqB2ncvlwDDYiw9JxZ2fsGa6O+qTdkQNfHB60T1YqESRBIbZED1PKwiZT5ijxjdqMIdn3g2t6GAZwvhLs6dJZHslyOMBny/e8IdzpMcFv5YK47eXG7eLsGvETyRBeenyPSMZzOE="
        on:
          tags: true